name: Build Blender PR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Disable Git LFS completely
        run: |
          git config --global filter.lfs.required false
          git config --global filter.lfs.smudge "git-lfs smudge --skip -- %f"
          git config --global filter.lfs.process "git-lfs filter-process --skip"
          git config --global filter.lfs.clean "git-lfs clean --skip -- %f"

      - name: Clone Blender manually
        shell: cmd
        run: |
          git clone https://projects.blender.org/blender/blender.git
          cd blender
          git fetch origin pull/153077/head:pr153077
          git checkout pr153077

      - name: Download Blender dependencies
        shell: cmd
        run: |
          cd blender
          build_files\utils\make_update.bat

      - name: Build Blender
        shell: cmd
        run: |
          cd blender
          build_files\windows\make.bat -j 2

      - name: Upload Blender build
        uses: actions/upload-artifact@v4
        with:
          name: blender-build
          path: blender/build_windows*
