name: Build Blender

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Git LFS
        run: |
          git lfs install

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Fetch PR
        shell: cmd
        run: |
          git fetch https://projects.blender.org/blender/blender.git pull/153077/head:pr153077
          git checkout pr153077

      - name: Pull LFS files
        run: git lfs pull

      - name: Download dependencies
        shell: cmd
        run: build_files\utils\make_update.bat

      - name: Build Blender
        shell: cmd
        run: build_files\windows\make.bat -j 2

      - name: Upload Blender build
        uses: actions/upload-artifact@v4
        with:
          name: blender-build
          path: build_windows*
